---
label: Default
hide_body: false
fields:
- type: number
  name: id
  label: id
- type: text
  name: title
  label: title
- type: datetime
  name: date
  label: date
- type: text
  name: author
  label: author
- type: text
  name: layout
  label: layout
- type: text
  name: guid
  label: guid
- type: text
  name: permalink
  label: permalink
- type: boolean
  name: featured
  label: featured
- type: file
  name: image
  label: image
- type: list
  name: categories
  label: categories
